#!/bin/bash

HEAD=`git symbolic-ref --short HEAD`
SHA=`git rev-parse HEAD`
SITE=site

if [ $# -eq 0 ]; then
echo "USAGE: $0 <files>" >&2
    exit 1
fi
if ! git diff --quiet; then
echo >&2
    echo "ERROR: working tree is dirty; aborting..." >&2
    echo >&2
    exit 2
fi
if ! git diff --quiet --cached; then
echo >&2
    echo "ERROR: index is dirty; aborting..." >&2
    echo >&2
    exit 2
fi

gh-pages(){
    git checkout gh-pages
    rm * -rf
    mv $SITE/* .
    git add -A
    git commit -m "$HEAD $SHA"
    mv * $SITE
    git checkout $HEAD
}

$*
