# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MrJoshuaP's Adventures
email: the@mrjoshuap.com
description: > # this means to ignore newlines until "baseurl:"
  Just a random technologist's ideas, thoughts and opinions peppered with
  a dash of enterprise open source and salted with bad humor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mrjoshuap.com" # the base hostname & protocol for your site
twitter_username: MrJoshuaP
github_username: mrjoshuap
linkedin_username: mrjoshuap
xboxlive_username: MrJoshuaP
timezone: America/New_York

exclude:
  - assets/satellite-6-release-automation.graffle
  - CNAME
  - Gemfile*
  - Makefile
  - shell
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Enable disqus comments
disqus:
  shortname: mrjoshuap

# Enable google analytics
google_analytics: UA-85143801-1

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/posts/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
sort_reverse: false

# Produces a cleaner folder structure when using categories
#permalink: /:year/:month/:title.html

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
